# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - vagrant
    - vagrant-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - vagrant
    - vagrant-install
