# tasks file
---
- ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - vagrant
    - vagrant-repository

- ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - vagrant
    - vagrant-install
