# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ vagrant_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - vagrant-repository-install-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: DA418C88A3219F7B
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags:
    - vagrant-repository-public-key

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ vagrant_repositories }}"
  tags:
    - vagrant-repository-add
